from django.urls import path

from new_app import views, seller_views, customer_views, admin_views

urlpatterns = [
    path("",views.home,name="home"),
    path("dashboard",views.dashboard,name="dashboard"),
    path("seller_form",seller_views.seller_form,name="seller_form"),
    path("customer_form",customer_views.customer_form,name="customer_form"),
    path("admin_base",admin_views.admin_base,name="admin_base"),
    path("customer_base",customer_views.customer_base,name="customer_base"),
    path("seller_base",seller_views.seller_base,name="seller_base"),
    path("login_view",views.login_view,name="login_view"),
    path("read_customer",admin_views.read_customer,name="read_customer"),
    path("edit_customer/<int:id>",admin_views.edit_customer,name="edit_customer"),
    path("delete_customer/<int:id>",admin_views.delete_customer,name="delete_customer"),
    path("read_seller", admin_views.read_seller, name="read_seller"),
    path("edit_seller/<int:id>", admin_views.edit_seller, name="edit_seller"),
    path("delete_seller/<int:id>", admin_views.delete_seller, name="delete_seller"),
    path("seller_profile", seller_views.seller_profile, name="seller_profile"),
    path("edit_seller_profile/<int:id>", seller_views.edit_seller_profile, name="edit_seller_profile"),
    path("customer_profile", customer_views.customer_profile, name="customer_profile"),
    path("edit_customer_profile/<int:id>", customer_views.edit_customer_profile, name="edit_customer_profile"),
    path("product_upload", seller_views.product_upload, name="product_upload"),
    path("product_view", customer_views.product_view, name="product_view"),
    path("product_filter", seller_views.product_filter, name="product_filter"),
    path("product_filter_edit/<int:id>", seller_views.product_filter_edit, name="product_filter_edit"),
    path("product_filter_delete/<int:id>", seller_views.product_filter_delete, name="product_filter_delete"),
    path("add_to_cart/<int:id>", customer_views.add_to_cart, name="add_to_cart"),
    path("view_cart", customer_views.view_cart, name="view_cart"),
    path("delete_item/<int:id>", customer_views.delete_item, name="delete_item"),
    path("buy_now/<int:id>", customer_views.buy_now, name="buy_now"),
    path("order_list", customer_views.order_list, name="order_list"),
    path("all_order", admin_views.all_order, name="all_order"),
    path("product_order_list", seller_views.product_order_list, name="product_order_list"),
]